### ISSUE TITLE
Broken on python 3.10

### ISSUE THREAD

**Issue by schrotie** [codota/tabnine-vim#107]
Tabnine does not work with python 3.10. I followed the suggestion in the related (closed) issue but that does not work for me. I'm on Manjaro (Arch based) Linux.
python: 3.10.1
vim:  8.2.4106

I'm not using pathogen, vundle or some such thing but the built-in native package loading of vim 8.

As recommended here I installed  https://github.com/tabnine/YouCompleteMe (in ~/.vim/pack/schrotie/start/YouCompleteMe and did _python3 install.py --all_ there) successfully.

I also switched ~/.vim/pack/schrotie/start/tabnine-vim to the python3 branch. I tried calling the install script there. _install.sh_ says it's deprecated and complains that urllib3 is missing (which is installed). _python3 install.py_ fails with:
```
Traceback (most recent call last):
  File "/home/schrotie/.vim/pack/schrotie/start/tabnine-vim/third_party/ycmd/build.py", line 50, in <module>
    import requests
  File "/home/schrotie/.vim/pack/schrotie/start/tabnine-vim/third_party/ycmd/third_party/requests/requests/__init__.py", line 134, in <module>
    from . import packages
ImportError: bad magic number in 'requests.packages': b'\x03\xf3\r\n'
```

When I then start vim I get a ton of errors. However, I'm not sure if it prints all problems ... there's quite some traces. Some are:
```
AttributeError: type object 'BaseRequest' has no attribute 'session'. Did you mean: 'Session'?
ImportError: bad magic number in 'requests.packages': [...]
E858: Eval did not return a valid python object
```

_Originally posted by @schrotie in https://github.com/codota/tabnine-vim/issues/103#issuecomment-1022046518_

gz#11533

**Comment by bilucodota** [comment]
Hi @schrotie .. can you clarify what happens exactly after you install tabnine/YouCompleteMe and open vim?

**Comment by schrotie** [comment]
Hi @bilucodota, thanks for your reply! I started vim with logging enabled and attached the log here:
[vim.log](https://github.com/codota/tabnine-vim/files/8010272/vim.log)
Note that this only occurs when I have the tabnine package on its python3 branch, not on master. I started gvim and the errors go in a loop, thus I have to kill it.

**Comment by bilucodota** [comment]
@schrotie can you try to delete all *.pyc files on your cloned repo?
`find . -name "*.pyc" -delete`

**Comment by schrotie** [comment]
@bilucodota That did it, thanks a lot!
Steps taken in the tabnine repo (with tabnine-ycm installed):
```
git checkout python3
find . -name "*.pyc" -delete
python3 install.py 
```
Then started vim, tabnine not working, did `:YcmRestartServer` and now it works again. Thanks!

**Comment by marslo** [comment]
> @bilucodota That did it, thanks a lot! Steps taken in the tabnine repo (with tabnine-ycm installed):
> 
> ```
> git checkout python3
> find . -name "*.pyc" -delete
> python3 install.py 
> ```
> 
> Then started vim, tabnine not working, did `:YcmRestartServer` and now it works again. Thanks! Please feel free to close this issue.

works for me on vim 9.0. details:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jul 12 2022 19:54:35)
macOS version - x86_64
Included patches: 1-49
```
